name: Issue/Epic/User Story
description: Template for an issue/epic/us
labels: ["issue"]
projects:
  - team-the-merge-doctors
body:
  - type: textarea
    attributes:
      label: User Story
      description: User story for this Epic.
      placeholder: As a user, I want to ..., so that ...
    validations:
      required: true
  - type: dropdown
    id: story_points
    attributes:
      label: Story Points
      description: Estimate the effort using story points
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
        - "13"
        - "21"
      default: 3
  
