--
-- PostgreSQL database dump
--

\restrict 24jRF4XLZ64zsDyVNvkfCBE6q8Cka6QlamaBcKeTfVMyT9c8iwIjlCYdwFN4b3K

-- Dumped from database version 17.7 (Debian 17.7-3.pgdg13+1)
-- Dumped by pg_dump version 17.7 (Debian 17.7-3.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: documentation; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.documentation (
    id bigint NOT NULL,
    content text,
    created_at timestamp(6) without time zone NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    project_id uuid NOT NULL
);


ALTER TABLE public.documentation OWNER TO admin;

--
-- Name: documentation_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.documentation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documentation_issues; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.documentation_issues (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    documentation_id bigint NOT NULL,
    issue_id bigint NOT NULL
);


ALTER TABLE public.documentation_issues OWNER TO admin;

--
-- Name: documentation_issues_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.documentation_issues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentation_issues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: issues; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.issues (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    priority smallint NOT NULL,
    status smallint NOT NULL,
    story_points integer NOT NULL,
    title character varying(255) NOT NULL,
    assignee_id bigint,
    creator_id bigint NOT NULL,
    project_id uuid NOT NULL,
    release_id bigint,
    sprint_id bigint,
    CONSTRAINT issues_priority_check CHECK (((priority >= 0) AND (priority <= 2))),
    CONSTRAINT issues_status_check CHECK (((status >= 0) AND (status <= 2)))
);


ALTER TABLE public.issues OWNER TO admin;

--
-- Name: issues_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.issues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.issues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.project (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    creator_id bigint NOT NULL
);


ALTER TABLE public.project OWNER TO admin;

--
-- Name: project_user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.project_user (
    project_id uuid NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.project_user OWNER TO admin;

--
-- Name: release; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.release (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    release_notes text,
    major integer,
    minor integer,
    patch integer,
    creator_id bigint NOT NULL,
    project_id uuid NOT NULL
);


ALTER TABLE public.release OWNER TO admin;

--
-- Name: release_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.release ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.release_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: release_issues; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.release_issues (
    release_id bigint NOT NULL,
    issues_id bigint NOT NULL
);


ALTER TABLE public.release_issues OWNER TO admin;

--
-- Name: sprints; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.sprints (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    end_date timestamp(6) without time zone NOT NULL,
    name character varying(255) NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    project_id uuid NOT NULL
);


ALTER TABLE public.sprints OWNER TO admin;

--
-- Name: sprints_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.sprints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sprints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tasks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    definition_of_done text,
    description text,
    status smallint NOT NULL,
    title character varying(255) NOT NULL,
    assignee_id bigint,
    creator_id bigint NOT NULL,
    issue_id bigint NOT NULL,
    project_id uuid NOT NULL,
    CONSTRAINT tasks_status_check CHECK (((status >= 0) AND (status <= 2)))
);


ALTER TABLE public.tasks OWNER TO admin;

--
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tests; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.tests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    program_code text NOT NULL,
    test_code text NOT NULL,
    creator_id bigint NOT NULL,
    issue_id bigint NOT NULL
);


ALTER TABLE public.tests OWNER TO admin;

--
-- Name: tests_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.tests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    enabled boolean DEFAULT true,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO admin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documentation_issues documentation_issues_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.documentation_issues
    ADD CONSTRAINT documentation_issues_pkey PRIMARY KEY (id);


--
-- Name: documentation documentation_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.documentation
    ADD CONSTRAINT documentation_pkey PRIMARY KEY (id);


--
-- Name: issues issues_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT issues_pkey PRIMARY KEY (id);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);


--
-- Name: project_user project_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.project_user
    ADD CONSTRAINT project_user_pkey PRIMARY KEY (project_id, user_id);


--
-- Name: release_issues release_issues_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.release_issues
    ADD CONSTRAINT release_issues_pkey PRIMARY KEY (release_id, issues_id);


--
-- Name: release release_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.release
    ADD CONSTRAINT release_pkey PRIMARY KEY (id);


--
-- Name: sprints sprints_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.sprints
    ADD CONSTRAINT sprints_pkey PRIMARY KEY (id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- Name: tests tests_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT tests_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: release_issues uk78wtg8eis7f4i2i2hb1o06f0x; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.release_issues
    ADD CONSTRAINT uk78wtg8eis7f4i2i2hb1o06f0x UNIQUE (issues_id);


--
-- Name: documentation_issues ukkwsay5gut35wsw6xlgm7k38g7; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.documentation_issues
    ADD CONSTRAINT ukkwsay5gut35wsw6xlgm7k38g7 UNIQUE (documentation_id, issue_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: project_user fk4ug72llnm0n7yafwntgdswl3y; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.project_user
    ADD CONSTRAINT fk4ug72llnm0n7yafwntgdswl3y FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: issues fk_assignee; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT fk_assignee FOREIGN KEY (assignee_id) REFERENCES public.users(id);


--
-- Name: tasks fk_assignee; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fk_assignee FOREIGN KEY (assignee_id) REFERENCES public.users(id);


--
-- Name: issues fk_issue_release; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT fk_issue_release FOREIGN KEY (release_id) REFERENCES public.release(id);


--
-- Name: issues fk_issue_sprint; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT fk_issue_sprint FOREIGN KEY (sprint_id) REFERENCES public.sprints(id);


--
-- Name: issues fk_project_creator; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT fk_project_creator FOREIGN KEY (creator_id) REFERENCES public.users(id);


--
-- Name: project fk_project_creator; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT fk_project_creator FOREIGN KEY (creator_id) REFERENCES public.users(id);


--
-- Name: release fk_project_creator; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.release
    ADD CONSTRAINT fk_project_creator FOREIGN KEY (creator_id) REFERENCES public.users(id);


--
-- Name: tasks fk_project_creator; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fk_project_creator FOREIGN KEY (creator_id) REFERENCES public.users(id);


--
-- Name: tests fk_project_creator; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT fk_project_creator FOREIGN KEY (creator_id) REFERENCES public.users(id);


--
-- Name: sprints fk_sprint_project; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.sprints
    ADD CONSTRAINT fk_sprint_project FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: release_issues fkb3s2ym2ev6olh717kpt6hr20; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.release_issues
    ADD CONSTRAINT fkb3s2ym2ev6olh717kpt6hr20 FOREIGN KEY (issues_id) REFERENCES public.issues(id);


--
-- Name: tests fke1set0oqgdoj6r7jwi48o6q0v; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT fke1set0oqgdoj6r7jwi48o6q0v FOREIGN KEY (issue_id) REFERENCES public.issues(id);


--
-- Name: tasks fkekeburt7kaq2chv97jybdxnfm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fkekeburt7kaq2chv97jybdxnfm FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: project_user fkfscw5rga2yu389e705x9wg6kb; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.project_user
    ADD CONSTRAINT fkfscw5rga2yu389e705x9wg6kb FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: issues fkg9pe16ifmx53tq3w9s49pajco; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT fkg9pe16ifmx53tq3w9s49pajco FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: release fkhmai3uwogjte55w6h0t6b6inh; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.release
    ADD CONSTRAINT fkhmai3uwogjte55w6h0t6b6inh FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: tasks fkinwx22oxglynw3rafukne2ntq; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT fkinwx22oxglynw3rafukne2ntq FOREIGN KEY (issue_id) REFERENCES public.issues(id);


--
-- Name: documentation fkj2hq78kym1loxoob91oiww804; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.documentation
    ADD CONSTRAINT fkj2hq78kym1loxoob91oiww804 FOREIGN KEY (project_id) REFERENCES public.project(id);


--
-- Name: release_issues fknxmts5836dkddrun3su682516; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.release_issues
    ADD CONSTRAINT fknxmts5836dkddrun3su682516 FOREIGN KEY (release_id) REFERENCES public.release(id);


--
-- Name: documentation_issues fkoadbnin2tfte990u0dapb05vs; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.documentation_issues
    ADD CONSTRAINT fkoadbnin2tfte990u0dapb05vs FOREIGN KEY (issue_id) REFERENCES public.issues(id);


--
-- Name: documentation_issues fkombnmncf3adgio0h1crdpereu; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.documentation_issues
    ADD CONSTRAINT fkombnmncf3adgio0h1crdpereu FOREIGN KEY (documentation_id) REFERENCES public.documentation(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 24jRF4XLZ64zsDyVNvkfCBE6q8Cka6QlamaBcKeTfVMyT9c8iwIjlCYdwFN4b3K

