name: CI – Pull Request

on:
  pull_request:
  workflow_call:

permissions: write-all

jobs:
  frontend-tests:
    uses: ./.github/workflows/frontend-tests.yml
  backend-tests:
    uses: ./.github/workflows/backend-tests.yml
