name: E2E (UI) Tests

on:
  workflow_call:

jobs:
  run-frontend-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: lts/*
          cache: 'npm' 
          cache-dependency-path: frontend/package-lock.json
        
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Run linting (ESLint)
        working-directory: ./frontend
        run: npm run lint || true  
      
      - name: Run unit tests (Vitest)
        working-directory: ./frontend
        run: npm run test:run 

      - name: Build frontend (Vite)
        working-directory: ./frontend
        run: npm run build

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build       
          path: ./frontend/dist
          retention-days: 7      
          overwrite: true        